---

- name: Set up firewall
  shell: systemctl enable firewalld

- name: Start the firewall
  shell: systemctl start firewalld

- name: package update
  yum: name=* state=latest

- name: Install epel-release
  yum: name=epel-release state=installed

- name: Install common tools
  yum: pkg={{ item }} state=installed
  with_items:
     - git
     - nano
     - curl
     - wget
     - vim
     - unzip
     - gcc
     - kernel-devel
     - kernel-headers
     - nmap

